services:

  # frontend / next js
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    networks:
      - aniflix-network

  # database / postgresql
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1984
    ports:
      - "5434:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - aniflix-network

  # Backend / Django
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
      - static_volume:/app/static 
      - media_volume:/app/media
    environment:
      DEBUG : "False"
      DB_NAME: "postgres"
      DB_USER: "postgres"
      DB_PASSWORD: "1984"
      DB_HOST: "postgres"
      DB_PORT: 5432
    networks:
      - aniflix-network

  # Nginx
  nginx:
    image: nginx:latest
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/static
      - media_volume:/media
    ports:
      - "80:80"
    networks:
      - aniflix-network
    depends_on:
      - backend

volumes:
  pg_data:
  static_volume:
  media_volume:
  
networks:
  aniflix-network:
    driver: bridge