# Generated by Django 5.1.2 on 2024-11-03 20:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('title_en', models.CharField(max_length=50)),
                ('title_ru', models.CharField(max_length=50)),
                ('genre', models.CharField(choices=[('Comedy', 'Комедии'), ('Cartoons', 'Мультфильмы'), ('Horror', 'Ужасы'), ('Fantastic', 'Фантастика'), ('Thrillers', 'Триллеры'), ('Fighters', 'Боевики'), ('Melodramas', 'Мелодрамы'), ('Detectives', 'Детективы'), ('Adventures', 'Приключения'), ('Fantasy', 'Фэнтези'), ('Military', 'Военные'), ('Family', 'Семейные'), ('Anime', 'Аниме'), ('Historical', 'Исторические'), ('Dramas', 'Драмы'), ('Documentary', 'Документальные'), ("Children's", 'Детские'), ('Crime', 'Криминал'), ('Biographies', 'Биографии'), ('Westerns', 'Вестерны'), ('Film Noir', 'Фильмы-нуар'), ('Sports', 'Спортивные'), ('Real TV', 'Реальное ТВ'), ('Short films', 'Короткометражки'), ('Musical', 'Музыкальные'), ('Musicals', 'Мюзиклы'), ('Talk show', 'Ток-шоу'), ('Games', 'Игры')], default='Comedy', max_length=50, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now, null=True)),
                ('description', models.CharField(max_length=130)),
            ],
        ),
    ]
