# Generated by Django 5.1.2 on 2024-11-04 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelvideo',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
