# Generated by Django 5.1.2 on 2024-11-04 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_modelvideo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelvideo',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
