# Generated by Django 5.1.2 on 2024-11-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_modelvideo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelvideo',
            name='main_genre',
            field=models.CharField(choices=[('Series', 'Сериалы'), ('Anime', 'Аниме'), ('Films', 'Фильмы')], default='Series', max_length=50, null=True),
        ),
    ]
