# Generated by Django 5.1.2 on 2024-11-07 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_modelvideo_main_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelvideo',
            name='main_genre',
            field=models.CharField(choices=[('series', 'Сериалы'), ('anime', 'Аниме'), ('films', 'Фильмы')], default='series', max_length=50, null=True),
        ),
    ]
